### ISSUE TITLE
 Exception: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by zhangdachen** [OpenDroneMap/Obj2Tiles#14] opened 2022-07-28 08:31 UTC
Exception: Index was outside the bounds of the array.

**Comment by zhangdachen** [comment] 2022-07-28 08:31
![image](https://user-images.githubusercontent.com/12945124/181459929-f767db07-8306-42dd-a213-17ee3186ec81.png)

**Comment by HeDo88TH** [comment] 2022-07-28 08:51
Hello, can you provide the input data?

**Comment by zhangdachen** [comment] 2022-07-28 09:18
I put the data  [here](https://github.com/zhangdachen/Models)
The command I execute is
`Obj2Tiles ..\Models\new_scene_0.obj ./output`

**Comment by zhangdachen** [comment] 2022-08-01 03:10
hello,
how is it，

**Comment by HeDo88TH** [comment] 2022-08-02 20:39
This is a bug, I can repro it but no solution is available yet

**Comment by uglyer** [comment] 2022-08-04 04:23
I also encountered this problem, the reason is that the `clusterBoundary` is less than a range of less than 0 when pack the texture, I will fix this problem later.

**Comment by zhangdachen** [comment] 2022-08-05 01:17
> I also encountered this problem, the reason is that the `clusterBoundary` is less than a range of less than 0 when pack the texture, I will fix this problem later.

能给打个包吗，我试试能不能行，电脑上没有core环境。

**Comment by HeDo88TH** [comment] 2022-08-05 09:59
Unfortunately #16 does not address the problem. The obj model is invalid since it has several texture coordinates > 1:

```
vt 2.0000 0.0000
vt 2.0000 0.4830
```

This is out of spec https://en.wikipedia.org/wiki/Wavefront_.obj_file#File_format .

**Comment by HeDo88TH** [comment] 2022-08-05 10:12
I will close this until new data comes up.

**Comment by HeDo88TH** [comment] 2022-09-20 22:47
Confirmed, waiting for fix 👍

**Comment by Rakiah** [comment] 2022-10-11 11:42
I'm having same issue

**Comment by Rakiah** [comment] 2022-10-12 12:32
using -k (keepTextures) works for me, i suppose the problems lies on the texture packing process

**Closed** 2022-10-24 10:56 UTC
Labels: bug

**Comment by uglyer** [comment] 2022-10-27 01:20
I misunderstood at first, uv is not limited to the range of 0~1, when the value is 1.5, it is consistent with 0.5
